site_name: Actividades
dev_addr: 127.0.0.1:8001
# site_url: 
# repo_url: 
# repo_name: <i class="fa fa-git"></i>

theme:
    name: mkdocs
    custom_dir: resources/
extra_css:
    - css/page.css
nav:
    - Individuales:
        - Investigacion 1 (Bonus): InvestigacionU1Bonus.md
        - Investigacion 2-1: InvestigacionU21.md
        - Investigacion 2-2: InvestigacionU22.md
        - Investigacion 3 (Bonus): InvestigacionU3Bonus.md
    - Colaborativas:
        - Actividad 1: todo.md
copyright: ©GMDXX
site_author: GMDXX
